version: "3"


x-base: &base
  user: "1000:1000"
  platform: linux/amd64
  build:
    context: .
    dockerfile: docker/backend.dockerfile
  environment:
    - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  volumes:
    - .:/code
  depends_on:
    - db

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    <<: *base
    command: uvicorn app:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"

  commands:
    <<: *base
    entrypoint: python -m directory.commands

  alembic:
    <<: *base
    entrypoint: alembic
    command: upgrade heads

  black:
    <<: *base
    entrypoint: black
    command: directory